### ISSUE TITLE
ortholog abundance correction for custom diamond database

### ISSUE THREAD

**Issue by maracashay** [borenstein-lab/MetaLAFFA#1]
Hi,

I performed 'create_gene_length_table.py" using a custom diamond database. I have attached a subset of the output from this command below. 

[A-Hedge-nrfA-subset-norm.txt](https://github.com/borenstein-lab/MetaLAFFA/files/5118866/A-Hedge-nrfA-subset-norm.txt)

Could you please explain what the numbers represent? Are they counts? Are they gene length (bps)? What exactly is normalized?

In the tutorial it is suggested to use "orthology_abundance_correction.py". I have changed method = relative as mentioned for non KO data. Could you please give me an example of how to use this command? 

Thank you!

**Comment by engal** [comment]
Hi,

The normalization table generated by 'create_gene_length_table.py' contains three pieces of information. At the top, included in a comment for reference, is the average gene length (bp) for all genes in the database. After that, there are three columns, the first is the name of the gene in the database, the second is the length of that gene (bp), and the third is the normalization factor relative to the average gene length (gene length/average gene length).

For your second question, if you have edited the ortholog_abundance_correction.py configuration file to change the method to 'relative', for relative abundance correction, that will be taken into account when you run the pipeline. You don't need to run anything separately or change anything else.

I should also note that the MetaLAFFA is currently undergoing a fair bit of change to make it easier to install and operate, and these changes may affect specifics of how you will need to run the pipeline.

Hope that helps!
