### ISSUE TITLE
Metatranscriptomes

### ISSUE THREAD

**Issue by bartns** [borenstein-lab/MetaLAFFA#2]
Hello, 
I quite like the pipeline you have developed here! 
Any reason why it can't be use on a metatranscriptome?

**Comment by engal** [comment]
Hi!

MetaLAFFA's default tools and settings were selected with metagenomic annotation in mind, though some tweaks could allow you to work with metatranscriptomic data. Specifically, MetaLAFFA does not include any metatranscriptomic-specific pre-processing steps (e.g. computational rRNA depletion) and the MUSiCC-based abundance correction step is specific to metagenomic read data. Sufficient modification of the pre-processing steps (or using a separate metatranscriptomic processing pipeline and using the resulting processed data as input to MetaLAFFA's read mapping step) and switching to relative abundance correction might allow you to use metatranscriptomic data, though we have not tested this.

Hope that helps!

**Comment by bartns** [comment]
Thanks for your answer and pointing out that MUSiCC step is designed more specifc for metagenomes. That will indeed need some looking into and testing!
