### ISSUE TITLE
bowtie2-align-s tbb library issue

### ISSUE THREAD

**Issue by BioMAs** [borenstein-lab/MetaLAFFA#3]
Hi, 

After installation via conda, cannot use bowtie2:

```
bowtie2 -h
bowtie2-align-s: symbol lookup error: bowtie2-align-s: undefined symbol: _ZN3tbb10interface78internal15task_arena_base19internal_initializeEv
(ERR): Description of arguments failed!
Exiting now ...
```

The problem seems to come from the tbb library.
Have any idea how to fix this problem?

**Comment by engal** [comment]
Hi,

I'm not exactly sure what's going on there. Could you try installing bowtie2 via conda in a separate, fresh conda environment and see if you get the same issue? If you don't get any errors there, then could you post the package list for that environment (output from 'conda list')?

Thanks!

**Comment by engal** [comment]
Not sure if you've managed to solve the issue on your own, but I've created a new release that includes a fix for the tbb issue.
