### ISSUE TITLE
Can't install metaLAFFA

### ISSUE THREAD

**Issue by zhouqCui** [borenstein-lab/MetaLAFFA#4]
Hi Sir,

I follow your instruction and update my Conda version to 4.10.1.

Then I run the command to install the metaLAFFA but failed. Below is the scripture. Would you please help me to fix it. Thanks.

(base) $ conda create -n metalaffa metalaffa -c bioconda -c borenstein-lab
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - metalaffa

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/borenstein-lab/osx-64
  - https://conda.anaconda.org/borenstein-lab/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by engal** [comment]
Hi,

Could you try running the following and let me know what happens:

conda create -n metalaffa metalaffa -c bioconda -c borenstein-lab/linux-64

**Comment by zhouqCui** [comment]
It works!!!! Thank you very much!

Have a good weekend!
Zhouqi

**Comment by engal** [comment]
Thanks for confirming that!

For future reference for anyone viewing this issue, the anaconda package repository was missing a build for OSX, I'll be uploading one shortly to fix the issue.

**Comment by s4251484** [comment]
Encountered the same issue! solved by following Engal's
